# Generated by Django 4.0.3 on 2022-04-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AidplannerApp', '0002_servicelist_itemlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlist',
            name='spot',
        ),
        migrations.AddField(
            model_name='itemlist',
            name='spot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AidplannerApp.spot'),
        ),
        migrations.RemoveField(
            model_name='servicelist',
            name='spot',
        ),
        migrations.AddField(
            model_name='servicelist',
            name='spot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AidplannerApp.spot'),
        ),
    ]
