# Generated by Django 4.0.3 on 2022-04-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AidplannerApp', '0003_remove_itemlist_spot_itemlist_spot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='spot',
        ),
    ]
