# Generated by Django 4.0.3 on 2022-04-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AidplannerApp', '0004_remove_service_spot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemList',
            new_name='CollectionItem',
        ),
        migrations.RenameModel(
            old_name='ServiceList',
            new_name='CollectionService',
        ),
    ]
