# Generated by Django 4.0.3 on 2022-04-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AidplannerApp', '0005_rename_itemlist_collectionitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitem',
            name='items',
        ),
        migrations.RemoveField(
            model_name='collectionservice',
            name='services',
        ),
    ]
