# Generated by Django 4.0.3 on 2022-04-08 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AidplannerApp', '0007_collectionitem_items_collectionservice_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCollectionItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_needed', models.IntegerField(null=True)),
                ('number_delivered', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCollectionServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_needed', models.IntegerField(null=True)),
                ('hours_needed', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='collectionservice',
            name='services',
        ),
        migrations.RemoveField(
            model_name='collectionservice',
            name='spot',
        ),
        migrations.RemoveField(
            model_name='item',
            name='number_delivered',
        ),
        migrations.RemoveField(
            model_name='item',
            name='number_needed',
        ),
        migrations.RemoveField(
            model_name='service',
            name='hours_needed',
        ),
        migrations.RemoveField(
            model_name='service',
            name='people_needed',
        ),
        migrations.DeleteModel(
            name='CollectionItem',
        ),
        migrations.DeleteModel(
            name='CollectionService',
        ),
        migrations.AddField(
            model_name='servicecollectionservices',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AidplannerApp.service'),
        ),
        migrations.AddField(
            model_name='servicecollectionservices',
            name='servicecollection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AidplannerApp.servicecollection'),
        ),
        migrations.AddField(
            model_name='servicecollection',
            name='services',
            field=models.ManyToManyField(through='AidplannerApp.ServiceCollectionServices', to='AidplannerApp.service'),
        ),
        migrations.AddField(
            model_name='servicecollection',
            name='spot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AidplannerApp.spot'),
        ),
        migrations.AddField(
            model_name='itemcollectionitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AidplannerApp.item'),
        ),
        migrations.AddField(
            model_name='itemcollectionitems',
            name='itemcollection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AidplannerApp.itemcollection'),
        ),
        migrations.AddField(
            model_name='itemcollection',
            name='items',
            field=models.ManyToManyField(through='AidplannerApp.ItemCollectionItems', to='AidplannerApp.item'),
        ),
        migrations.AddField(
            model_name='itemcollection',
            name='spot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AidplannerApp.spot'),
        ),
    ]
